/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package velora;

import java.awt.Image;
import java.awt.Window;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import java.text.NumberFormat;
import java.util.Locale;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author X1 Carbon Gen 8
 */
public class Produk extends javax.swing.JInternalFrame {

    /**
     * Creates new form Produk
     */
    public Produk() {
        initComponents();
        tampilTabel();
        setVisible(true);
        setClosable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();
        link = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsi = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        pathGambar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        skin_type = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fungsi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namaProduk = new javax.swing.JTextField();
        idProduk = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelGambar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("MENU PRODUK");
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(840, 1200));

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NO", "ID", "NAMA", "FUNGSI", "DESKRIPSI", "TIPE WAJAH", "HARGA", "FOTO", "LINK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Byte.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelProdukMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelProduk);

        link.setBackground(new java.awt.Color(238, 151, 191));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Link");

        deskripsi.setBackground(new java.awt.Color(238, 151, 191));
        deskripsi.setColumns(20);
        deskripsi.setRows(5);
        jScrollPane1.setViewportView(deskripsi);

        jButton6.setBackground(new java.awt.Color(151, 169, 205));
        jButton6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Pilih Foto");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        pathGambar.setBackground(new java.awt.Color(238, 151, 191));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Deskripsi");

        skin_type.setBackground(new java.awt.Color(238, 151, 191));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Skin Type");

        harga.setBackground(new java.awt.Color(238, 151, 191));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Harga");

        fungsi.setBackground(new java.awt.Color(238, 151, 191));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fungsi");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nama");

        namaProduk.setBackground(new java.awt.Color(238, 151, 191));

        idProduk.setEditable(false);
        idProduk.setBackground(new java.awt.Color(240, 191, 213));
        idProduk.setDisabledTextColor(new java.awt.Color(239, 192, 214));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Id");

        jButton1.setBackground(new java.awt.Color(151, 169, 205));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(151, 169, 205));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Bersih");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(151, 169, 205));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(151, 169, 205));
        jButton3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Ubah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(75, 75, 75)
                        .addComponent(idProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(link)
                            .addComponent(skin_type)
                            .addComponent(harga)
                            .addComponent(fungsi)
                            .addComponent(namaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addComponent(labelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(pathGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fungsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(skin_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(link, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();

        // Menambahkan filter untuk file gambar
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Image Files", "jpg", "jpeg", "png", "gif", "bmp");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String fullPath = selectedFile.getAbsolutePath(); // Mengambil path lengkap
            pathGambar.setText(fullPath); // Menyimpan path lengkap ke JTextField

            try {
                // Load the image to display in the label
                ImageIcon imageIcon = new ImageIcon(fullPath);
                int labelWidth = labelGambar.getWidth();
                int labelHeight = labelGambar.getHeight();

                // Resize the image to fit the label
                int imageWidth = imageIcon.getIconWidth();
                int imageHeight = imageIcon.getIconHeight();
                double scaleX = (double) labelWidth / imageWidth;
                double scaleY = (double) labelHeight / imageHeight;
                double scale = Math.min(scaleX, scaleY);

                Image scaledImage = imageIcon.getImage().getScaledInstance(
                        (int) (scale * imageWidth),
                        (int) (scale * imageHeight),
                        Image.SCALE_SMOOTH
                );

                labelGambar.setIcon(new ImageIcon(scaledImage));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Failed to load image: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        deleteProduct();
        tampilTabel();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        updateProduct();
        tampilTabel();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        createProduct();
        bersih();
        tampilTabel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelProdukMouseClicked
        // TODO add your handling code here:
        int baris = tabelProduk.rowAtPoint(evt.getPoint());

        String id = tabelProduk.getValueAt(baris, 1).toString();
        idProduk.setText(id);

        String productName = tabelProduk.getValueAt(baris, 2).toString();
        namaProduk.setText(productName);

        String function = tabelProduk.getValueAt(baris, 3).toString();
        fungsi.setText(function);

        String productDescription = tabelProduk.getValueAt(baris, 4).toString();
        deskripsi.setText(productDescription);

        String price = tabelProduk.getValueAt(baris, 6).toString();
        harga.setText(price);

        String skinType = tabelProduk.getValueAt(baris, 5).toString();
        skin_type.setText(skinType);

        String imagePath = tabelProduk.getValueAt(baris, 7).toString(); // Indeks 7 untuk image path
        pathGambar.setText(imagePath);

        String recommendationLink = tabelProduk.getValueAt(baris, 8).toString(); // Indeks 8 untuk rekomendasi link
        link.setText(recommendationLink);

        if (imagePath != null && !imagePath.isEmpty()) {
            try {
                File imageFile = new File(imagePath);
                ImageIcon imageIcon = new ImageIcon(imageFile.getAbsolutePath());

                // Ambil ukuran label
                int labelWidth = labelGambar.getWidth();
                int labelHeight = labelGambar.getHeight();

                // Ambil ukuran gambar asli
                int imageWidth = imageIcon.getIconWidth();
                int imageHeight = imageIcon.getIconHeight();

                // Hitung skala untuk memperkecil gambar agar sesuai dengan label
                double scaleX = (double) labelWidth / imageWidth;
                double scaleY = (double) labelHeight / imageHeight;
                double scale = Math.min(scaleX, scaleY); // Ambil skala terkecil

                // Ubah ukuran gambar sesuai skala
                Image scaledImage = imageIcon.getImage().getScaledInstance(
                        (int) (scale * imageWidth),
                        (int) (scale * imageHeight),
                        Image.SCALE_SMOOTH
                );

                labelGambar.setIcon(new ImageIcon(scaledImage)); // Menampilkan gambar skala
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Failed to load image: " + e.getMessage());
            }
        }


    }//GEN-LAST:event_tabelProdukMouseClicked

    private String selectedImagePath;

    private void createProduct() {
        String productName = namaProduk.getText();
        String productDescription = deskripsi.getText();
        String recommendationLink = link.getText();
        String price = harga.getText();
        String skinType = skin_type.getText();
        String function = fungsi.getText();

        if (productName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi nama produk dulu");
            return;
        } else if (function.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi fungsi produk dulu");
            return;
        } else if (price.isEmpty() || !price.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Isi harga produk dengan angka yang valid");
            return;
        } else if (skinType.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi jenis kulit produk dulu");
            return;
        } else if (recommendationLink.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi link produk dulu");
            return;
        } else if (productDescription.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi deskripsi produk dulu");
            return;
        } else if (pathGambar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan gambar terlebih dahulu");
            return;
        }

        String imagePath = pathGambar.getText();

        byte[] imageBytes = null;
        if (selectedImagePath != null && !selectedImagePath.isEmpty()) {
            try {
                File imageFile = new File(selectedImagePath);
                imageBytes = Files.readAllBytes(imageFile.toPath());
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Gagal Memuat gambar: " + e.getMessage());
                return;
            }
        }

        try {
            String sql = "INSERT INTO products (product_name, function, product_description, skin_type, product_price, product_image, recommendation_links) VALUES (?, ?, ?, ?, ?, ?, ?)";

            Connection Vconn = Koneksi.konfigDB();
            java.sql.PreparedStatement ps = Vconn.prepareStatement(sql);

            ps.setString(1, productName);
            ps.setString(2, function);
            ps.setString(3, productDescription);
            ps.setString(4, skinType);
            ps.setInt(5, Integer.valueOf(price));
            ps.setString(6, pathGambar.getText());
            ps.setString(7, recommendationLink);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Produk berhasil ditambahkan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal tambah produk: " + e.getMessage());
        }
    }

    private void updateProduct() {
        String id = idProduk.getText();
        String productName = namaProduk.getText();
        String productDescription = deskripsi.getText();
        String recommendationLink = link.getText();
        String price = harga.getText();
        String skinType = skin_type.getText();
        String function = fungsi.getText();
        String imagePath = pathGambar.getText();

        if (productName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi nama produk dulu");
            return;
        } else if (function.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi fungsi produk dulu");
            return;
        } else if (price.isEmpty() || !price.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Isi harga produk dengan angka yang valid");
            return;
        } else if (skinType.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi jenis kulit produk dulu");
            return;
        } else if (recommendationLink.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi link produk dulu");
            return;
        } else if (productDescription.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi deskripsi produk dulu");
            return;
        } else if (pathGambar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan gambar terlebih dahulu");
            return;
        } else {

            try {
                String sql = "UPDATE products SET product_name=?, function=?, product_description=?, skin_type=?, product_price=?, product_image=?, recommendation_links=? WHERE id=?";

                Connection Vconn = Koneksi.konfigDB(); // Assuming you have a DB connection
                java.sql.PreparedStatement ps = Vconn.prepareStatement(sql);

                ps.setString(1, productName);
                ps.setString(2, function);
                ps.setString(3, productDescription);
                ps.setString(4, skinType);
                ps.setInt(5, Integer.valueOf(price));
                ps.setString(6, imagePath);
                ps.setString(7, recommendationLink);
                ps.setString(8, id); // ID untuk WHERE clause

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Produk berhasil di ubah");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "gagal ubah produk: " + e.getMessage());
            }
        }

    }

    private void deleteProduct() {
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this product?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String id = idProduk.getText();

            try {
                String sql = "DELETE FROM products WHERE id=?";

                Connection Vconn = Koneksi.konfigDB(); // Assuming you have a DB connection
                java.sql.PreparedStatement ps = Vconn.prepareStatement(sql);
                ps.setString(1, id); // ID untuk WHERE clause

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Produk berhasil di hapus");
                tampilTabel(); // Refresh the table after deletion
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "gagal hapus produk: " + e.getMessage());
            }
        }
    }

    public void tampilTabel() {
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("NO");
        tb.addColumn("ID");
        tb.addColumn("NAMA");
        tb.addColumn("FUNGSI");
        tb.addColumn("DESKRIPSI");
        tb.addColumn("SKIN TYPE");
        tb.addColumn("HARGA");
        tb.addColumn("FOTO");
        tb.addColumn("LINK");

        try {

            int count = 1;

            //1. query
            String query = "SELECT * FROM products";
            //2. oneksi
            Connection Vconn = (Connection) Koneksi.konfigDB();
            //3 kirim parameter Java ke Sql
            Statement s = Vconn.createStatement();
            //4. eksekusi query
            ResultSet r = s.executeQuery(query);
            //5. Looping
            
             NumberFormat formatRupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
            
            while (r.next()) {
                tb.addRow(new Object[]{
                    count++,
                    r.getString("id"), // Ambil berdasarkan nama kolom
                    r.getString("product_name"),
                    r.getString("function"),
                    r.getString("product_description"),
                    r.getString("skin_type"),
                    formatRupiah.format(r.getInt("product_price")), // Memformat harga/ Pastikan ini sesuai dengan tipe kolom
                    r.getString("product_image"),
                    r.getString("recommendation_links")
                });
            }
            tabelProduk.setModel(tb);

        } catch (Exception ex) {

        }

    }

    private void bersih() {
        idProduk.setText("");
        namaProduk.setText("");
        deskripsi.setText("");
        fungsi.setText("");
        harga.setText("");
        link.setText("");
        skin_type.setText("");
        labelGambar.setIcon(null);
        pathGambar.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea deskripsi;
    private javax.swing.JTextField fungsi;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField idProduk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelGambar;
    private javax.swing.JTextField link;
    private javax.swing.JTextField namaProduk;
    private javax.swing.JTextField pathGambar;
    private javax.swing.JTextField skin_type;
    private javax.swing.JTable tabelProduk;
    // End of variables declaration//GEN-END:variables

    private void tampiTabel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
